### ISSUE TITLE
在IDOL数据集上测试效果与论文出入较大

### ISSUE THREAD

**Issue by xiangyudxy** [zju3dv/rnin-vio#1]
你好，我使用IDOL提供的旋转矩阵对iphone的数据转换，变换到激光设备的坐标系下，如下所示：
Note the iPhone and Stencil IMU raw measurements are not in the same reference frames. The Stencil IMU reference frame and ground truth reference frame are the same. The frames are roughly mapped as Stencil +x -> iPhone -x, Stencil +y -> iPhone -y, Stencil +z -> iPhone +z in right-handed coordinate frames。
并对acc数据乘以9.8保证尺度，激光真值数据未作变换。以这样的数据进行训练，最终模型在测试集上的平均Ate：6.9，与论文中的平均Ate：4.28 相差较大。请问你们对idol数据集做了什么样的处理？这部分的代码方便分享吗？谢谢！

**Comment by danpeng2** [comment]
你好，我们的对比是在Raw Stencil IMU上进行的。


祝好！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju3dv/rnin-vio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月7日(星期一) 下午5:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zju3dv/rnin-vio] 在IDOL数据集上测试效果与论文出入较大 (Issue #1)





 
你好，我使用IDOL提供的旋转矩阵对iphone的数据转换，变换到激光设备的坐标系下，如下所示：
 Note the iPhone and Stencil IMU raw measurements are not in the same reference frames. The Stencil IMU reference frame and ground truth reference frame are the same. The frames are roughly mapped as Stencil +x -&gt; iPhone -x, Stencil +y -&gt; iPhone -y, Stencil +z -&gt; iPhone +z in right-handed coordinate frames。
 并对acc数据乘以9.8保证尺度，激光真值数据未作变换。以这样的数据进行训练，最终模型在测试集上的平均Ate：6.9，与论文中的平均Ate：4.28 相差较大。请问你们对idol数据集做了什么样的处理？这部分的代码方便分享吗？谢谢！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BUG423** [comment]
> 你好，我使用IDOL提供的旋转矩阵对iphone的数据转换，变换到激光设备的坐标系下，如下所示： Note the iPhone and Stencil IMU raw measurements are not in the same reference frames. The Stencil IMU reference frame and ground truth reference frame are the same. The frames are roughly mapped as Stencil +x -> iPhone -x, Stencil +y -> iPhone -y, Stencil +z -> iPhone +z in right-handed coordinate frames。 并对acc数据乘以9.8保证尺度，激光真值数据未作变换。以这样的数据进行训练，最终模型在测试集上的平均Ate：6.9，与论文中的平均Ate：4.28 相差较大。请问你们对idol数据集做了什么样的处理？这部分的代码方便分享吗？谢谢！

你好，我也与同样的问题，并且我正在多个数据集上进行测试（RONIN、RIDI、TLIO、OxIOD等等），或许我们可以交流数据处理方案
