### ISSUE TITLE
How do you get the bias in the IMU dataset you provide?

### ISSUE THREAD

**Issue by StiphyJay** [zju3dv/rnin-vio#3]
Hello,

Thank you very much for your great work. I am very interested in your work. 
But I have some confusion. How did you get the ground truth value of the IMU dataset? At the same time, how are the bias of accelerometers and gyroscopes obtained in your IMU dataset?  Do you use a tightly coupled system to estimate the pose and IMU  bias as the ground-truth value of the data set?

Because IMU bias is often difficult to obtain in practical applications, could you explain this?

Looking forward to your reply!

Best

**Comment by danpeng2** [comment]
We use visual-inertial odometry to provide the IMU bias on our dataset. The traditional visual-inertial odometry can usually provide accurate IMU bias. However, the estimated bias is not completely accurate, so during training, we will perform data augmentation based on the possible bias error range.
