### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../data_train/'

### ISSUE THREAD

**Issue by hiXiaoYU** [zju3dv/rnin-vio#6]
Sorry to bother you, I use the server to run the code, but this error occurred, what should I do 

Traceback (most recent call last):
  File "main_net.py", line 182, in <module>
    train_data_path = GetDataPath(cfg['data']['train_dir'])
  File "main_net.py", line 44, in GetDataPath
    names = os.listdir(path+"/")
FileNotFoundError: [Errno 2] No such file or directory: '../data_train/'

**Comment by danpeng2** [comment]
You need to modify the dataset path in the 'config/default.yam' file. Best Wish!

**Comment by hiXiaoYU** [comment]
Thankyou! it is running now.

**Comment by hiXiaoYU** [comment]
Sorry to bother you. Your idea in this paper is pretty good and I want to collect my own data and reproduce your code, can you tell me how you collect, process data and finally achieve the result of visual display?
thanks！

**Comment by danpeng2** [comment]
We use multiple smartphones to collect data with cameras and IMUs. Then, we use visual-inertial odometry to provide the supervised positions aligned with gravity at IMU frequency on the dataset. The dataset format refers to our open-source dataset. You can use python to plot INS trajectories and pangolin to show visual results.
